### PR TITLE
Adding grafana dashboard - no automation yet

### PR DESCRIPTION
**Pull request by csibbitt**
* templated job to be minishift/quicklab agnostic
* added additional service monitors
  * prometheus
  * qdr
* added two dashboards
  * default prometheus-specific monitoring board
  * custom SAF perf monitoring board

### CODE REVIEW

**Comment by csibbitt** [comment]
Hey @pleimer ; I was hoping we could get these merged in and then add them to the existing automation. (See https://trello.com/c/Q6Lor0Br/681-adjust-perftest-automation-to-handle-new-servicemonitors-and-dashboards#) if you'd prefer to just work off this branch and submit a new PR when the automation is complete, that is cool too!

**Comment by leifmadsen** [comment]
Nothing in here bothers me, and it looks pretty separate. I say go ahead and merge it down.

**Comment by pleimer** [comment]
Yeah that's fine, I will work off this branch. Don't delete it!

**Comment by csibbitt** [comment]
I don't like merging with these :x: 's showing, but gonna do it anyways. I'll burn some time today figuring out what is wrong with our smoketest.

**Pull request merged**
